apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: airflow-logs-pv
  resources:
    requests:
      storage: 5Gi